#!/bin/bash
# script to accept arguments sending in from git mergetool
#
# Base is $1
# Remote (or Theirs) is $2
# Local (or Yours) is $3
# Merged is $4
vimdiff -c "wincmd J" -c "windo set wrap" "$4" "$3" "$1" "$2"

# or try
# git config merge.tool vimdiff
# git config merge.conflictstyle diff3
# git config mergetool.prompt false

# https://www.rosipov.com/blog/use-vimdiff-as-git-mergetool/
